declare enum NodeType {
    WEB_HOOK = "WEB_HOOK",
    FETCH_DATA = "FETCH_DATA",
    DECLAR_VARIABLE = "DECLAR_VARIABLE",
    CONDITION = "CONDITION",
    LOOP = "LOOP",
    BASIC_CACULATION = "BASIC_CACULATION",
    HTTP_RESPONSE = "HTTP_RESPONSE",
    SCHEDULE = "SCHEDULE",
    DELAY = "DELAY",
    SEND_EMAIL = "SEND_EMAIL",
    HTML_RESPONSE = "HTML_RESPONSE",
    INSERT_ROW = "INSERT_ROW",
    REDIRECT = "REDIRECT",
    MOUDLE_START = "MOUDLE_START",
    MOUDLE_END = "MOUDLE_END",
    SCRIPT_MOUDLE = "SCRIPT_MOUDLE"
}
export default NodeType;
